version: '3'

services: 
  hr-config-server:
    build: 
      dockerfile: ./docker/hr-config-server.dockerfile
      context: .
    image: matheusmv/hr-config-server:0.0.1
    container_name: hr-config-server
    # environment: 
    #   - GITHUB_USER=
    #   - GITHUB_PASS=
    ports: 
      - "8888:8888"
    networks:
      - hr-net
    restart: unless-stopped

  hr-eureka-server:
    build: 
      dockerfile: ./docker/hr-eureka-server.dockerfile
      context: .
    image: matheusmv/hr-eureka-server:0.0.1
    container_name: hr-eureka-server 
    ports: 
      - "8761:8761"
    networks:
      - hr-net
    restart: unless-stopped

  hr-oauth:
    build: 
      dockerfile: ./docker/hr-oauth.dockerfile
      context: .
    image: matheusmv/hr-oauth:0.0.1
    container_name: hr-oauth
    environment:
      - eureka.client.service-url.defaultZone=http://hr-eureka-server:8761/eureka
      - spring.cloud.config.uri=http://hr-config-server:8888
    networks:
      - hr-net
    restart: unless-stopped
    depends_on: 
      - hr-config-server
      - hr-eureka-server
      - hr-user

  hr-api-gateway-zuul:
    build: 
      dockerfile: ./docker/hr-api-gateway-zuul.dockerfile
      context: .
    image: matheusmv/hr-api-gateway-zuul:0.0.1
    container_name: hr-api-gateway-zuul
    environment:
      - eureka.client.service-url.defaultZone=http://hr-eureka-server:8761/eureka
      - spring.cloud.config.uri=http://hr-config-server:8888
    ports: 
      - "8765:8765"
    networks:
      - hr-net
    restart: unless-stopped
    depends_on: 
      - hr-config-server
      - hr-eureka-server

  hr-workerdb-pg13:
    build: 
      dockerfile: ./docker/hr-workerdb.dockerfile
      context: .
    image: matheusmv/hr-workerdb-pg13:0.0.1
    container_name: hr-workerdb-pg13
    ports:
      - "5432:5432"
    networks:
      - hr-net
    restart: unless-stopped

  hr-worker:
    build: 
      dockerfile: ./docker/hr-worker.dockerfile
      context: .
    image: matheusmv/hr-worker:0.0.1
    container_name: hr-worker
    environment:  
      - SPRING_PROFILES_ACTIVE=dev
      - eureka.client.service-url.defaultZone=http://hr-eureka-server:8761/eureka
      - spring.cloud.config.uri=http://hr-config-server:8888
    networks:
      - hr-net
    restart: unless-stopped
    depends_on: 
      - hr-config-server
      - hr-eureka-server
      - hr-workerdb-pg13

  hr-userdb-pg13:
    build: 
      dockerfile: ./docker/hr-userdb.dockerfile
      context: .
    image: matheusmv/hr-userdb-pg13:0.0.1
    container_name: hr-userdb-pg13
    ports:
      - "5433:5432"
    networks:
      - hr-net
    restart: unless-stopped

  hr-user:
    build: 
      dockerfile: ./docker/hr-user.dockerfile
      context: .
    image: matheusmv/hr-user:0.0.1
    container_name: hr-user
    environment:  
      - SPRING_PROFILES_ACTIVE=dev
      - eureka.client.service-url.defaultZone=http://hr-eureka-server:8761/eureka
      - spring.cloud.config.uri=http://hr-config-server:8888
    networks:
      - hr-net
    restart: unless-stopped
    depends_on: 
      - hr-config-server
      - hr-eureka-server
      - hr-userdb-pg13

  hr-payroll:
    build: 
      dockerfile: ./docker/hr-payroll.dockerfile
      context: .
    image: matheusmv/hr-payroll:0.0.1
    container_name: hr-payroll
    environment:
      - eureka.client.service-url.defaultZone=http://hr-eureka-server:8761/eureka
    networks:
      - hr-net
    restart: unless-stopped
    depends_on: 
      - hr-eureka-server
      - hr-worker

networks:
  hr-net:
    name: hr-net
    driver: bridge